"use client";

import { useState, useMemo } from "react";
import { Button } from "@repo/ui";
import { Input } from "@repo/ui";
import { Text } from "@repo/ui";
import type {
  Category,
  CategoryCreateInput,
  CategoryUpdateInput,
} from "@repo/domain";
import { CategoryConfigEditor } from "./CategoryConfigEditor";

interface CategoryFormProps {
  category?: Category;
  onSubmit: (data: CategoryCreateInput | CategoryUpdateInput) => void;
  onCancel: () => void;
  isLoading?: boolean;
}

export function CategoryForm({
  category,
  onSubmit,
  onCancel,
  isLoading,
}: CategoryFormProps) {
  const [name, setName] = useState(category?.name || "");
  const [key, setKey] = useState(category?.key || "");
  const [slug, setSlug] = useState(category?.slug || "");
  const [iconName, setIconName] = useState(category?.iconName || "");
  const [description, setDescription] = useState(category?.description || "");
  const [sortOrder, setSortOrder] = useState(category?.sortOrder || 0);
  const [isActive, setIsActive] = useState(category?.isActive ?? true);
  const [configJson, setConfigJson] = useState<Record<string, unknown> | null>(
    category?.configJson || null
  );
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false);
  const [keyManuallyEdited, setKeyManuallyEdited] = useState(false);

  // Auto-generate slug and key from name if not editing
  // Use derived state that updates when name changes
  const autoGeneratedSlug = useMemo(() => {
    if (category || !name) return "";
    return name
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "") // Remove accents
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "");
  }, [name, category]);

  const autoGeneratedKey = useMemo(() => {
    if (category || !name) return "";
    return name
      .toUpperCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "") // Remove accents
      .replace(/[^A-Z0-9]+/g, "_")
      .replace(/(^_|_$)/g, "");
  }, [name, category]);

  // Use auto-generated values if slug/key haven't been manually edited
  const displaySlug = slugManuallyEdited ? slug : slug || autoGeneratedSlug;
  const displayKey = keyManuallyEdited ? key : key || autoGeneratedKey;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const formData: CategoryCreateInput | CategoryUpdateInput = {
      name,
      key: displayKey,
      slug: displaySlug,
      sortOrder,
      isActive,
      ...(iconName && { iconName }),
      ...(description && { description }),
      ...(configJson && { configJson }),
    };

    onSubmit(formData);
  };

  const hasChanges =
    name !== (category?.name || "") ||
    displayKey !== (category?.key || "") ||
    displaySlug !== (category?.slug || "") ||
    iconName !== (category?.iconName || "") ||
    description !== (category?.description || "") ||
    sortOrder !== (category?.sortOrder || 0) ||
    isActive !== (category?.isActive ?? true) ||
    JSON.stringify(configJson) !== JSON.stringify(category?.configJson || null);

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Nombre <span className="text-red-500">*</span>
          </label>
          <Input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
            placeholder="Ej: Plomería"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Clave <span className="text-red-500">*</span>
          </label>
          <Input
            type="text"
            value={displayKey}
            onChange={(e) => {
              setKey(e.target.value.toUpperCase());
              setKeyManuallyEdited(true);
            }}
            required
            placeholder="Ej: PLUMBING"
            disabled={!!category} // Key cannot be changed after creation
          />
          {category && (
            <Text variant="xs" className="text-gray-500 mt-1">
              La clave no puede cambiarse después de la creación
            </Text>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Slug <span className="text-red-500">*</span>
          </label>
          <Input
            type="text"
            value={displaySlug}
            onChange={(e) => {
              setSlug(
                e.target.value
                  .toLowerCase()
                  .replace(/[^a-z0-9-]/g, "-")
                  .replace(/-+/g, "-")
                  .replace(/(^-|-$)/g, "")
              );
              setSlugManuallyEdited(true);
            }}
            required
            placeholder="Ej: plumbing"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Nombre del Icono
          </label>
          <Input
            type="text"
            value={iconName}
            onChange={(e) => setIconName(e.target.value)}
            placeholder="Ej: Wrench"
          />
          <Text variant="xs" className="text-gray-500 mt-1">
            Nombre del icono de Lucide React
          </Text>
        </div>

        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Descripción
          </label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            rows={3}
            className="w-full px-3 py-2 border border-gray-300 rounded-md bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
            placeholder="Descripción de la categoría"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Orden de clasificación
          </label>
          <Input
            type="number"
            value={sortOrder}
            onChange={(e) => setSortOrder(parseInt(e.target.value) || 0)}
            min={0}
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Estado
          </label>
          <label className="flex items-center">
            <input
              type="checkbox"
              checked={isActive}
              onChange={(e) => setIsActive(e.target.checked)}
              className="rounded border-gray-300 text-primary focus:ring-primary"
            />
            <span className="ml-2 text-sm text-gray-700">Activa</span>
          </label>
        </div>
      </div>

      {/* Config JSON Editor */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Configuración JSON
        </label>
        <CategoryConfigEditor value={configJson} onChange={setConfigJson} />
      </div>

      {/* Form Actions */}
      <div className="flex items-center justify-end gap-2 pt-4 border-t">
        <Button type="button" variant="ghost" onClick={onCancel}>
          Cancelar
        </Button>
        <Button type="submit" disabled={!hasChanges || isLoading}>
          {isLoading ? "Guardando..." : category ? "Actualizar" : "Crear"}
        </Button>
      </div>
    </form>
  );
}
