"use client";

import { useState, useMemo } from "react";
import { Button } from "@repo/ui";
import { Input } from "@repo/ui";
import { Text } from "@repo/ui";
import { useCategories } from "@/hooks/useCategories";
import type { Subcategory } from "@repo/domain";
import { SubcategoryConfigEditor } from "./SubcategoryConfigEditor";

interface SubcategoryFormData {
  name: string;
  slug: string;
  categoryId: string;
  imageUrl?: string | null;
  description?: string | null;
  displayOrder: number;
  isActive: boolean;
  configJson?: Record<string, unknown> | null;
}

interface SubcategoryFormProps {
  subcategory?: Subcategory;
  initialCategoryId?: string;
  onSubmit: (data: SubcategoryFormData) => void;
  onCancel: () => void;
  isLoading?: boolean;
}

export function SubcategoryForm({
  subcategory,
  initialCategoryId,
  onSubmit,
  onCancel,
  isLoading,
}: SubcategoryFormProps) {
  const { data: categories } = useCategories();
  const [name, setName] = useState(subcategory?.name || "");
  const [slug, setSlug] = useState(subcategory?.slug || "");
  const [categoryId, setCategoryId] = useState(
    subcategory?.categoryId || initialCategoryId || ""
  );
  const [imageUrl, setImageUrl] = useState(subcategory?.imageUrl || "");
  const [description, setDescription] = useState(
    subcategory?.description || ""
  );
  const [displayOrder, setDisplayOrder] = useState(
    subcategory?.displayOrder || 0
  );
  const [isActive, setIsActive] = useState(subcategory?.isActive ?? true);
  const [configJson, setConfigJson] = useState<Record<string, unknown> | null>(
    null
  ); // Note: configJson not in current domain schema
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false);

  // Auto-generate slug from name if not editing
  // Use derived state that updates when name changes
  const autoGeneratedSlug = useMemo(() => {
    if (subcategory || !name) return "";
    return name
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "") // Remove accents
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "");
  }, [name, subcategory]);

  // Use auto-generated value if slug hasn't been manually edited
  const displaySlug = slugManuallyEdited ? slug : slug || autoGeneratedSlug;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const formData: SubcategoryFormData = {
      name,
      slug: displaySlug,
      categoryId,
      displayOrder,
      isActive,
      ...(imageUrl && { imageUrl }),
      ...(description && { description }),
      ...(configJson && { configJson }),
    };

    onSubmit(formData);
  };

  const hasChanges =
    name !== (subcategory?.name || "") ||
    displaySlug !== (subcategory?.slug || "") ||
    categoryId !== (subcategory?.categoryId || "") ||
    imageUrl !== (subcategory?.imageUrl || "") ||
    description !== (subcategory?.description || "") ||
    displayOrder !== (subcategory?.displayOrder || 0) ||
    isActive !== (subcategory?.isActive ?? true);

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Nombre <span className="text-red-500">*</span>
          </label>
          <Input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
            placeholder="Ej: Desatascos"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Categoría <span className="text-red-500">*</span>
          </label>
          <select
            value={categoryId}
            onChange={(e) => setCategoryId(e.target.value)}
            required
            disabled={!!subcategory} // Category cannot be changed after creation
            className="w-full px-3 py-2 border border-gray-300 rounded-md bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
          >
            <option value="">Seleccionar categoría</option>
            {categories
              ?.filter((c) => !c.deletedAt && c.isActive)
              .map((category) => (
                <option key={category.id} value={category.id}>
                  {category.name}
                </option>
              ))}
          </select>
          {subcategory && (
            <Text variant="xs" className="text-gray-500 mt-1">
              La categoría no puede cambiarse después de la creación
            </Text>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Slug <span className="text-red-500">*</span>
          </label>
          <Input
            type="text"
            value={displaySlug}
            onChange={(e) => {
              setSlug(
                e.target.value
                  .toLowerCase()
                  .replace(/[^a-z0-9-]/g, "-")
                  .replace(/-+/g, "-")
                  .replace(/(^-|-$)/g, "")
              );
              setSlugManuallyEdited(true);
            }}
            required
            placeholder="Ej: desatascos"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            URL de Imagen
          </label>
          <Input
            type="url"
            value={imageUrl}
            onChange={(e) => setImageUrl(e.target.value)}
            placeholder="https://example.com/image.jpg"
          />
        </div>

        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Descripción
          </label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            rows={3}
            className="w-full px-3 py-2 border border-gray-300 rounded-md bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
            placeholder="Descripción de la subcategoría"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Orden de visualización
          </label>
          <Input
            type="number"
            value={displayOrder}
            onChange={(e) => setDisplayOrder(parseInt(e.target.value) || 0)}
            min={0}
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Estado
          </label>
          <label className="flex items-center">
            <input
              type="checkbox"
              checked={isActive}
              onChange={(e) => setIsActive(e.target.checked)}
              className="rounded border-gray-300 text-primary focus:ring-primary"
            />
            <span className="ml-2 text-sm text-gray-700">Activa</span>
          </label>
        </div>
      </div>

      {/* Config JSON Editor */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Configuración JSON (opcional)
        </label>
        <Text variant="xs" className="text-gray-500 mb-2">
          Esta configuración sobrescribe la configuración de la categoría padre
        </Text>
        <SubcategoryConfigEditor value={configJson} onChange={setConfigJson} />
      </div>

      {/* Form Actions */}
      <div className="flex items-center justify-end gap-2 pt-4 border-t">
        <Button type="button" variant="ghost" onClick={onCancel}>
          Cancelar
        </Button>
        <Button
          type="submit"
          disabled={!hasChanges || isLoading || !categoryId}
        >
          {isLoading ? "Guardando..." : subcategory ? "Actualizar" : "Crear"}
        </Button>
      </div>
    </form>
  );
}
